CREATE DATABASE IF NOT EXISTS `CONSTRUCAO`;

USE `CONSTRUCAO`;

CREATE TABLE `ENGENHEIRO` (
  `ENG_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `ENG_NOME` VARCHAR(30) DEFAULT NULL,
  `ENG_APELIDO` VARCHAR(15) DEFAULT NULL,
  `ENG_TELEFONE` VARCHAR(15) DEFAULT NULL,
  `ENG_CREA` VARCHAR(6) DEFAULT NULL,
  `ENG_DTFORMATURA` DATE,
  PRIMARY KEY (`ENG_CODIGO`)
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=LATIN1;

CREATE TABLE `OBRA` (
  `OBR_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `OBR_CIDADE` VARCHAR(20) DEFAULT NULL,
  `OBR_TIPO` VARCHAR(10) DEFAULT NULL,
  `OBR_VALOR` DECIMAL(12,2) DEFAULT NULL,
  `OBR_INICIOOBRA` DATE,
  `ENG_CODIGO` INT NOT NULL,
  PRIMARY KEY (`OBR_CODIGO`),
  CONSTRAINT `FK_OBRA_ENGENHEIRO` FOREIGN KEY (`ENG_CODIGO`) REFERENCES `ENGENHEIRO`(`ENG_CODIGO`)
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=LATIN1;

